### ISSUE TITLE
Encrypt and decrypt files on storage

### ISSUE THREAD

**Issue by Presto412** [Presto412/CryptoFS#10]
Files stored aren't encrypted, only the metadata is. You can add encryption to files uploaded and decrypt them on download.

**Comment by chris--jones** [comment]
Hey @Presto412 wouldn't mind having a crack at this one as well.

**Comment by Presto412** [comment]
@chris--jones sure, thanks!

**Comment by chris--jones** [comment]
I've been experimenting with crypto on the browser side anyhow, so thank you for the learning opportunity 😉

**Comment by chris--jones** [comment]
@Presto412 - I experimented with encrypting in the browser and it's possible, but I have some encoding and hash check issues to solve if we go down this path. It also places a limit on the size of files you can upload as they have to be processed in local memory.

Is this the point of this issue or should I look at solely encrypting and decrypting on the server side (probably considerably easier)?

I am presently using part of the signature as inputs into AES, but I would anticipate further extensions to this application to either store additional keys and allow different algorithm choice.

**Comment by Presto412** [comment]
@chris--jones We can add asynchronous encryption to the server side, that is okay(user can refresh to get the status of upload or equivalent).

However if you're trying to tackle it in the browser, and learn something new, maybe you can split the input stream into chunks, encrypt them and send them in batches (requiring some modification in the backend as well) to solve the memory issue. 
You can check this [link](https://stackoverflow.com/questions/33889410/proper-way-to-implement-restful-large-file-upload) to get an idea.

**Comment by chris--jones** [comment]
I'm not trying to tackle the file size issue yet, in my mind having a working example and proving the concept will pave the way for future extensions like what you are describing. The benefit of encrypting the files in the browser is that you could store the keys locally then only the user can decrypt them (most secure).

**Comment by Presto412** [comment]
Sure then, you can proceed with browser based encryption. Let's look at the
large file issue later.

Regards,
Priyansh Jain

**Comment by chris--jones** [comment]
I've solved the encoding problem for downloads, now I'm just trying to resolve the hashing issue and fix the UI as I'm now uploading via fetch. Progress here: https://github.com/chris--jones/CryptoFS/tree/file-encryption
