### ISSUE TITLE
Setup prettify, editorconfig, eslint and add a github action as a pre-commit hook for the same

### ISSUE THREAD

**Issue by Presto412** [Presto412/CryptoFS#16]
Currently, formatting in different editors may yield to conflicts, so it would help if we have a standard way to do this.

**Comment by opensourceally** [comment]
I can pickup the same.

**Comment by Presto412** [comment]
Sure @opensourceally . Assigning you to it. Thanks!

**Comment by opensourceally** [comment]
PR  #17 created for the same. Please check and let me know.
