### ISSUE TITLE
Add a docker-compose file for mongodb + npm setup

### ISSUE THREAD

**Issue by Presto412** [Presto412/CryptoFS#7]
Currently, it is required to install MongoDB for running the app, so you can help Dockerize it and add a compose file with mongodb and the app itself to launch with one command. The versions used are specified in the README

**Comment by AlexandreL0pes** [comment]
Hi, I will work on this. :)

**Comment by Presto412** [comment]
Great, thanks!

**Comment by AlexandreL0pes** [comment]
I think that mongo and node are working now, if there's another necessary change, just tell me. 
#11
